---
- hosts: '{{ target }}}}'
  gather_facts: false
  connection: local

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Create security rules
      panos_security_rule:
        provider: '{{ device }}'
        rule_name: '{{ item.name }}'
        source_zone: ['untrust']
        destination_zone: ['trust']
        source_ip: ['any']
        destination_ip: '{{ item.destination }}'
        application: '{{ item.application }}'
        service: ['application-default']
        action: 'allow'
        tag_name: '{{ item.tag }}'
        commit: False
      with_items:
        - { name: 'Prod SSH Inbound', destination: ['Prod-Instances'], application: ['ssh'], tag: ['Prod'] }
        - { name: 'SI Inbound', destination: ['SI-Instances'], application: ['ssh', 'mysql'], tag: ['SI'] }
