---
# fw_rule_survey.yml - Add security rule via Ansible Tower survey.
#
# Description
# ===========
#
# This is similar to 'fw_rules.yml', but the variables can be overridden using the output of an Ansible Tower survey.
#
# Connection details for the device must be specified in the 'device' variable, see 'vars.yml'.
#
# Modules Used
# ============
#
# panos_security_rule - https://ansible-pan.readthedocs.io/en/latest/modules/panos_security_rule_module.html
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory fw_rule_survey.yml

- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars.yml

  vars:
    rule_name: 'Survey Rule'
    source_zone: 'trust'
    source_ip: 'any'
    destination_zone: 'untrust'
    destination_ip: 'any'
    application:
      - 'any'
    service:
      - 'application-default'

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Create security rule via extra_vars
      panos_security_rule:
        provider: '{{ device }}'
        rule_name: '{{ rule_name }}'
        source_zone: '{{ source_zone }}'
        destination_zone: '{{ destination_zone }}'
        source_ip: '{{ source_ip }}'
        destination_ip: '{{ destination_ip }}'
        application: '{{ application }}'
        service: '{{ service }}'
        action: 'allow'
        tag_name: '{{ tag|default([]) }}'
        commit: false
