---
# fw_shutdown.yml - Shuts down a PAN-OS device.
#
# Description
# ===========
#
# This issues the shutdown command using the 'panos_op' module.  This uses the Ansible 'ignore_errors' keyword because
# issuing the shutdown command terminates the API connection.
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory fw_shutdown.yml

- hosts: firewall
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Issue firewall shutdown command
      panos_op:
        provider: '{{ device }}'
        cmd: '<request><shutdown><system></system></shutdown></request>'
        cmd_is_xml: true
      ignore_errors: true
